/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyecto;

import java.awt.JobAttributes;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class Insertar extends javax.swing.JFrame {

    String matri = "no";
    String reser = "no";
    String admiti = "no";
    int opcion;
    
    

    public Insertar() {
        initComponents();
        setLocationRelativeTo(null);
        cCentro.add(pTelefono);
        cCentro.add(pWeb);
        cCentro.add(pPresencial);
        cCentro.add(pEmail);
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/IconoCES.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cCentro = new javax.swing.ButtonGroup();
        confAlarma = new javax.swing.JDialog();
        jLabelEmail = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        mailAlarma = new javax.swing.JTextField();
        informacion = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        apellido1 = new javax.swing.JTextField();
        localidad = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        cpostal = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        dni = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        admitido = new javax.swing.JCheckBox();
        reserva = new javax.swing.JCheckBox();
        matricula = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        pTelefono = new javax.swing.JRadioButton();
        pEmail = new javax.swing.JRadioButton();
        pPresencial = new javax.swing.JRadioButton();
        pWeb = new javax.swing.JRadioButton();
        Panel = new Panel("/Imagenes/LogoCES.png");
        jLabel1 = new javax.swing.JLabel();
        apellido2 = new javax.swing.JTextField();

        jLabel5.setText("jLabel1");

        jLabel4.setText("jLabel1");

        jLabel7.setText("jLabel1");

        confAlarma.setTitle("Configuración de alerta");
        confAlarma.setAlwaysOnTop(true);
        confAlarma.setBounds(new java.awt.Rectangle(0, 0, 455, 200));
        confAlarma.setResizable(false);

        jLabelEmail.setText("E-mail:");

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        mailAlarma.setToolTipText("Introduce el E-mail receptor de la alerta");

        informacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        informacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        informacion.setText("Introduce el E-mail donde llegará el aviso");

        confAlarma.setLocationRelativeTo(null);

        javax.swing.GroupLayout confAlarmaLayout = new javax.swing.GroupLayout(confAlarma.getContentPane());
        confAlarma.getContentPane().setLayout(confAlarmaLayout);
        confAlarmaLayout.setHorizontalGroup(
            confAlarmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confAlarmaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(confAlarmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(confAlarmaLayout.createSequentialGroup()
                        .addComponent(jLabelEmail)
                        .addGap(46, 46, 46)
                        .addComponent(mailAlarma)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, confAlarmaLayout.createSequentialGroup()
                        .addGroup(confAlarmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(confAlarmaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(aceptar))
                            .addComponent(informacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39))))
        );
        confAlarmaLayout.setVerticalGroup(
            confAlarmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confAlarmaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(informacion)
                .addGap(18, 18, 18)
                .addGroup(confAlarmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(mailAlarma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(aceptar)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Cliente");

        nombre.setToolTipText("Introduce el nombre del cliente");
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        apellido1.setToolTipText("Introduce los apellidos del cliente");
        apellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellido1ActionPerformed(evt);
            }
        });

        localidad.setToolTipText("Introduce localidad");
        localidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localidadActionPerformed(evt);
            }
        });

        email.setToolTipText("Introduce E-mail del cliente");

        cpostal.setToolTipText("Introduce el codigo postal");

        telefono.setToolTipText("Introduce numero de telefono");

        dni.setToolTipText("Introduce el DNI");

        jLabel10.setText("Apellido1:");

        jLabel11.setText("Localidad:");

        jLabel12.setText("CPostal:");

        jLabel13.setText("DNI:");

        jLabel14.setText("E-Mail:");

        jLabel15.setText("Telefono:");

        jLabel16.setText("Admitido:");

        jLabel17.setText("Reserva:");

        jLabel18.setText("Matricula:");

        jLabel19.setText("Nombre:");

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        admitido.setToolTipText("¿Esta admitido? si/no ");
        admitido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admitidoActionPerformed(evt);
            }
        });

        reserva.setToolTipText("¿Ha reservado? si/no");
        reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservaActionPerformed(evt);
            }
        });

        matricula.setToolTipText("¿Esta matriculado? si/no");
        matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculaActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("¿Cómo ha conocido el centro?")));

        pTelefono.setText("Telefono");
        pTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pTelefonoActionPerformed(evt);
            }
        });

        pEmail.setText("E-mail");
        pEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pEmailActionPerformed(evt);
            }
        });

        pPresencial.setText("Presencial");
        pPresencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pPresencialActionPerformed(evt);
            }
        });

        pWeb.setText("Web");
        pWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pWebActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pTelefono)
                    .addComponent(pEmail)
                    .addComponent(pPresencial)
                    .addComponent(pWeb))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pTelefono)
                .addGap(18, 18, 18)
                .addComponent(pEmail)
                .addGap(18, 18, 18)
                .addComponent(pPresencial)
                .addGap(18, 18, 18)
                .addComponent(pWeb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("Apellido 2:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel19))
                                .addGap(47, 47, 47))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(44, 44, 44)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(apellido1)
                            .addComponent(nombre)
                            .addComponent(apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16)
                                .addComponent(jLabel17)
                                .addComponent(jLabel18))
                            .addGap(45, 45, 45)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dni)
                                    .addComponent(cpostal)
                                    .addComponent(localidad)
                                    .addComponent(email, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(telefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(admitido)
                                        .addComponent(reserva)
                                        .addComponent(matricula))
                                    .addGap(192, 192, 192)
                                    .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(localidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(admitido))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(reserva))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(matricula)))
                    .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellido1ActionPerformed

    private void localidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localidadActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String tl = telefono.getText();
        String cpos=cpostal.getText();
        int tlf = Integer.parseInt(tl);
        int cp = Integer.parseInt(cpos);
        
        
        OpClientes ins = new OpClientes(nombre.getText(), apellido1.getText(), apellido2.getText(), localidad.getText(), cp, dni.getText(), email.getText(), tlf, admiti, reser, matri);
        ins.insertar();
        
        JOptionPane.showMessageDialog(null,"Usuario registrado correctamente");
        
        confAlarma.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void admitidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admitidoActionPerformed
        if (admitido.isSelected()) {
            admiti = "si";
        } else {
            admiti = "no";
        }
    }//GEN-LAST:event_admitidoActionPerformed

    private void reservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservaActionPerformed
        if (reserva.isSelected()) {
            reser = "si";
        } else {
            reser = "no";
        }
    }//GEN-LAST:event_reservaActionPerformed

    private void matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaActionPerformed
        if (matricula.isSelected()) {
            matri = "si";
        } else {
            matri = "no";
        }
    }//GEN-LAST:event_matriculaActionPerformed

    private void pTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pTelefonoActionPerformed
        // TODO add your handling code here:
        opcion = 1;
    }//GEN-LAST:event_pTelefonoActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here
        String dMensaje = "nombre: " + nombre.getText()+ "\n" +"apellidos: " + apellido1.getText() + " " + apellido2.getText() +"\n" + "Telefono: " + telefono.getText() + "\n" + "Correo: " + email.getText()+ "\n";
        switch (opcion){
            case 1:
                dMensaje += "Llamar para concertar una cita";
                Correo alarma1 = new Correo("desarrollador.93.04.17@gmail.com", "nezsesszqpuqxcuk", mailAlarma.getText(), "Alarma: Llamada por telefono", dMensaje);
                alarma1.sendMail();
                dispose();
            break;
                
            case 2:
                dMensaje += "Llamar para concertar una cita o enviar un correo";
                Correo alarma2 = new Correo("desarrollador.93.04.17@gmail.com", "nezsesszqpuqxcuk", mailAlarma.getText(), "Alarma: solicitud por correo", dMensaje);
                alarma2.sendMail();
                dispose();
            break;
            
            case 3:
                dMensaje += "Enviar correo para pedirle la documentación";
                Correo alarma3 = new Correo("desarrollador.93.04.17@gmail.com", "nezsesszqpuqxcuk", mailAlarma.getText(), "Alarma: solicitud presencial", dMensaje);
                alarma3.sendMail();
                dispose();
            break;
                
            case 4:
                dMensaje += "Enviar correo para pedirle la documentación";
                Correo alarma4 = new Correo("desarrollador.93.04.17@gmail.com", "nezsesszqpuqxcuk", mailAlarma.getText(), "Alarma: solicitud vía web", dMensaje);
                alarma4.sendMail();
                dispose();
            break;
        }
        
        
    }//GEN-LAST:event_aceptarActionPerformed

    private void pEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pEmailActionPerformed
        // TODO add your handling code here:
        opcion = 2;
    }//GEN-LAST:event_pEmailActionPerformed

    private void pPresencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pPresencialActionPerformed
        // TODO add your handling code here:
        opcion = 3;
    }//GEN-LAST:event_pPresencialActionPerformed

    private void pWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pWebActionPerformed
        // TODO add your handling code here:
        opcion = 4;
    }//GEN-LAST:event_pWebActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insertar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton aceptar;
    private javax.swing.JCheckBox admitido;
    private javax.swing.JTextField apellido1;
    private javax.swing.JTextField apellido2;
    private javax.swing.ButtonGroup cCentro;
    private javax.swing.JDialog confAlarma;
    private javax.swing.JTextField cpostal;
    private javax.swing.JTextField dni;
    private javax.swing.JTextField email;
    private javax.swing.JLabel informacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField localidad;
    private javax.swing.JTextField mailAlarma;
    private javax.swing.JCheckBox matricula;
    private javax.swing.JTextField nombre;
    private javax.swing.JRadioButton pEmail;
    private javax.swing.JRadioButton pPresencial;
    private javax.swing.JRadioButton pTelefono;
    private javax.swing.JRadioButton pWeb;
    private javax.swing.JCheckBox reserva;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
